# permissions for end users to view superservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: superservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
  name: superservice-viewer-role
rules:
- apiGroups:
  - tech.example.io
  resources:
  - superservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tech.example.io
  resources:
  - superservices/status
  verbs:
  - get
