apiVersion: tech.example.io/v1
kind: SuperService
metadata:
  labels:
    app.kubernetes.io/name: superservice
    app.kubernetes.io/instance: superservice-sample
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo
  name: superservice-sample
spec:
  # TODO(user): Add fields here
